[versions]
lombok = "1.18.30"
datafaker = "2.3.0"
junit-jupiter = "5.8.1"

[libraries]
lombok = {module = "org.projectlombok:lombok", version.ref = "lombok"}
datafaker = {module = "net.datafaker:datafaker", version.ref = "datafaker"}
junit-jupiterl = {module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter"}