[versions]
lombok = "1.18.34"
junitJupiter = "5.10.0"
datafaker = "2.0.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
datafaker = { module = "net.datafaker:datafaker", version.ref = "datafaker" }